springdoc:
  packagesToScan: com.springboot.api
  swagger-ui:
    operationsSorter: alpha
    tagsSorter: alpha
  
  defult-flat-paramObject: true


#TRACE>DEBUG>INFO>WARN>ERROR>OFF
logging:
  config: classpath:log4j2.yml
  level:
    org.springframework: info
    com.springboot: debug

spring:
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/springboot1
    username: webuser1
    password: webuser1
  jpa:
    hibernate:
      ddl-auto: create
      show-sql: true
      properties:
        hibernate:
          format_sql: true